name: Build Backend

on:
  push:
    branches: [ rust-backend ]
  pull_request:
    branches: [ rust-backend ]

env:
  CARGO_TERM_COLOR: always

jobs:
   
  build:
    defaults:
      run:
        working-directory: n2-station
        
    runs-on: ubuntu-latest

    services:
      mariadb:
        image: mariadb:latest
        ports:
          - 3306
        env:
          MYSQL_DATABASE: n2station
          MYSQL_ROOT_PASSWORD: root
        options: --health-cmd="mysqladmin ping" --health-interval=5s --health-timeout=2s --health-retries=3

    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v2
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
    - name: Prepare tables
      env:
          PORT: ${{ job.services.mariadb.ports[3306] }}
      run: mysql --user="root" --password="root" --database="n2station" -h"127.0.0.1" -P"$PORT" < "../setup.sql"
    - name: Build
      run: cargo build --verbose --release
    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        path: ${{ github.workspace }}/target/release/n2-station
        name: 'n2-station'
